server:
  host: ${HOST:127.0.0.1}
  port: ${PORT:8080}
# context-path: /prod-api
  grpc:
    port: ${PORT_GRPC:18080}

application:
  name: app
  active: dev
  cache-type: redis # redis ram
  cache-tpl: false # 默认不缓存模板,省内存，方便开发
  resources-path: resources # 默认资源目录，存放配置文件、静态资源、模板
  upload-path: resources/static/upload # 默认资源目录，存放配置文件、静态资源、模板

#cloud:
#  nacos:
#    discovery:       # 服务注册地址
#      server-addr:  192.168.88.106
#      port: 8848
copyright: © 2025 dpc.com Copyright